### ISSUE TITLE
Compilation error with RN 0.57

### ISSUE THREAD

**Issue by zedtux** [avwave/rn-doc-scanner-android#5]
I followed the instructions from the `README.md` file of this repo and I'm stuck with this when I'm running `react-native run-android` :

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.google.android.gms:play-services-vision' has different version for the compile (11.8.0) and runtime (15.0.2) classpath. You should manually set the same version via DependencyResolution
```

**Comment by veb** [comment]
This was tested working on `"react-native": "0.55.1"` so we'd have to look into why it's no longer working on RN 0.57 unless you want to do a PR. 👍

**Comment by zedtux** [comment]
I would have liked to open a PR solving this, but I'm really new to Android world and I don't have a clue how to solve this issue 😞.

**Comment by veb** [comment]
Have a try now @zedtux

**Comment by zedtux** [comment]
@veb I'll try it tomorrow.

**Comment by zedtux** [comment]
So I tried again and I have the same error again.

I double check the code from my `node_modules` folder, in order to be sure to get the latest version from the PR, and the code is the same.

Then I updated my `android/build.gradle` in order to set the `googlePlayServicesVersion` to 15.0.2 but then I got the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find com.google.android.gms:play-services-gcm:15.0.2.
  Searched in the following locations:
  file:/Users/zedtux/...
  file:/Users/zedtux/...
  file:/Users/zedtux/...
  file:/Users/zedtux/...
  https://jcenter.bintray.com/com/google/android/gms/play-services-gcm/15.0.2/play-services-gcm-15.0.2.pom
  https://jcenter.bintray.com/com/google/android/gms/play-services-gcm/15.0.2/play-services-gcm-15.0.2.jar
  ...
  Required by:
      project :app > project :react-native-device-info
> Could not find com.google.android.gms:play-services-basement:15.0.2.
  Searched in the following locations:
  file:/Users/zedtux/...
  file:/Users/zedtux/...
  file:/Users/zedtux/...
  file:/Users/zedtux/...
  https://jcenter.bintray.com/com/google/android/gms/play-services-basement/15.0.2/play-services-basement-15.0.2.pom
  https://jcenter.bintray.com/com/google/android/gms/play-services-basement/15.0.2/play-services-basement-15.0.2.jar
  ...
  Required by:
      project :app > project :rn-doc-scanner
> Could not find com.google.android.gms:play-services-basement:15.0.2.
  Searched in the following locations:
  file:/Users/zedtux/...
  file:/Users/zedtux/...
  file:/Users/zedtux/...
  file:/Users/zedtux/...
  https://jcenter.bintray.com/com/google/android/gms/play-services-basement/15.0.2/play-services-basement-15.0.2.pom
  https://jcenter.bintray.com/com/google/android/gms/play-services-basement/15.0.2/play-services-basement-15.0.2.jar
  ...
  Required by:
      project :app > project :rn-doc-scanner > com.google.android.gms:play-services-vision:15.0.2
      project :app > project :rn-doc-scanner > com.google.android.gms:play-services-vision:15.0.2 > com.google.android.gms:play-services-vision-common:15.0.2
      project :app > project :rn-doc-scanner > com.google.android.gms:play-services-vision:15.0.2 > com.google.android.gms:play-services-vision-common:15.0.2 > com.google.android.gms:play-services-clearcut:15.0.1
      project :app > project :rn-doc-scanner > com.google.android.gms:play-services-vision:15.0.2 > com.google.android.gms:play-services-vision-common:15.0.2 > com.google.android.gms:play-services-phenotype:15.0.1
> Could not find com.google.android.gms:play-services-basement:15.0.2.
  Searched in the following locations:
  file:/Users/zedtux/...
  file:/Users/zedtux/...
  file:/Users/zedtux/...
  file:/Users/zedtux/...
  https://jcenter.bintray.com/com/google/android/gms/play-services-basement/15.0.2/play-services-basement-15.0.2.pom
  https://jcenter.bintray.com/com/google/android/gms/play-services-basement/15.0.2/play-services-basement-15.0.2.jar
  ...
  Required by:
      project :app > project :rn-doc-scanner > com.google.android.gms:play-services-vision:15.0.2 > com.google.android.gms:play-services-base:15.0.1
      project :app > project :rn-doc-scanner > com.google.android.gms:play-services-vision:15.0.2 > com.google.android.gms:play-services-base:15.0.1 > com.google.android.gms:play-services-tasks:15.0.1
      project :app > project :rn-doc-scanner > com.google.android.gms:play-services-vision:15.0.2 > com.google.android.gms:play-services-vision-common:15.0.2 > com.google.android.gms:play-services-flags:15.0.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

Here is my `android/build.gradle` file:

```
buildscript {
    ext {
        // Picking your compileSdkVersion, minSdkVersion, and targetSdkVersion :
        // https://medium.com/androiddevelopers/picking-your-compilesdkversion-minsdkversion-targetsdkversion-a098a0341ebd
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 26
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "15.0.2"
    }
    // ...
}
// ...
```

I'm quite new to all the Android world so please if you could guide me 😅.

**Comment by Pompette** [comment]
Try to remove googlePlayServicesVersion from ext, and add it to dependencies :
```java
buildscript {
    repositories {
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'
        classpath 'com.google.gms:google-services:+'
    }
}

**Comment by zedtux** [comment]
I still have the error :

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.google.android.gms:play-services-vision' has different version for the compile (11.8.0) and runtime (15.0.2) classpath. You should manually set the same version via DependencyResolution
```

So, just to be sure I'm not missing something, let me post my Android files.

- `android/build.gradle` :
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.
// https://medium.com/androiddevelopers/picking-your-compilesdkversion-minsdkversion-targetsdkversion-a098a0341ebd

buildscript {
    ext {
        // Picking your compileSdkVersion, minSdkVersion, and targetSdkVersion :
        // https://medium.com/androiddevelopers/picking-your-compilesdkversion-minsdkversion-targetsdkversion-a098a0341ebd
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 26
        supportLibVersion = "28.0.0"
    }
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'
        classpath 'com.google.gms:google-services:+'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        google()
        maven {
            url "http://dl.bintray.com/steveliles/maven"
        }
    }
}

// Dirty fix for react-native-sensitive-info
// and potentially for react-native-image-to-pdf
// See https://github.com/mCodex/react-native-sensitive-info/issues/117
subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
            }
        }
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}
```

- `android/app/build.gradle` :
```
apply plugin: "com.android.application"
apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js",
    nodeExecutableAndArgs: ["node", "--max_old_space_size=8192"]
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * react-native-vector-icons
 */
project.ext.vectoricons = [
    iconFontNames: [ 'FontAwesome.ttf', 'Ionicons.ttf' ]
]

apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"


/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    defaultConfig {
        applicationId "com.mycorp.companion"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 40
        versionName "1.1.5"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation project(':rn-fetch-blob')
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-sensitive-info')
    implementation project(':react-native-pdf')
    implementation project(':react-native-linear-gradient')
    implementation project(':react-native-image-to-pdf')
    implementation project(':react-native-i18n')
    implementation project(':react-native-document-scanner')
    implementation project(':react-native-device-info')
    implementation project(':react-native-config')
    implementation (project(':react-native-camera')) {
        exclude group: "com.android.support"
    }
    implementation project(':react-native-autogrow-textinput')
    implementation project(':rn-doc-scanner')
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
```

- `android/settings.gradle`:
```
rootProject.name = 'Companion'
include ':rn-doc-scanner'
project(':rn-doc-scanner').projectDir = new File(rootProject.projectDir, '../node_modules/rn-doc-scanner/android')
include ':rn-fetch-blob'
project(':rn-fetch-blob').projectDir = new File(rootProject.projectDir, '../node_modules/rn-fetch-blob/android')
include ':react-native-vector-icons'
project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons/android')
include ':react-native-sensitive-info'
project(':react-native-sensitive-info').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-sensitive-info/android')
include ':react-native-pdf'
project(':react-native-pdf').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-pdf/android')
include ':react-native-linear-gradient'
project(':react-native-linear-gradient').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-linear-gradient/android')
include ':react-native-image-to-pdf'
project(':react-native-image-to-pdf').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-image-to-pdf/android')
include ':react-native-i18n'
project(':react-native-i18n').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-i18n/android')
include ':react-native-document-scanner'
project(':react-native-document-scanner').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-document-scanner/android')
include ':react-native-device-info'
project(':react-native-device-info').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-device-info/android')
include ':react-native-config'
project(':react-native-config').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-config/android')
include ':react-native-camera'
project(':react-native-camera').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-camera/android')
include ':react-native-autogrow-textinput'
project(':react-native-autogrow-textinput').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-autogrow-textinput/android')

include ':app'
```

Do you see anything wrong I did ?

**Comment by Pompette** [comment]
What if you put ?
```java
ext {
    buildToolsVersion = "27.0.3"
    minSdkVersion = 16
    compileSdkVersion = 27
    targetSdkVersion = 26
    supportLibVersion = "27.1.1"
    googlePlayServicesVersion = "+"
}
```

The problem is that you have conflict between 2 packages that ask different version of gcm, I think it's react-native-device-info, you may have to upgrade this package either

**Comment by zedtux** [comment]
Thank you @Pompette, the compilation went fine. I'm now implementing it and I'll update you. 👍

**Comment by zedtux** [comment]
The package now works, but I'm disappointed by what the package does. When I saw that the project has OpenCV as a dependency, I was expecting an auto detection of the page which is not the case, I only has the manual cropping feature.

Should this package auto-detect the page or not?

Anyway, the issue solved, thank you all for your help.

**Comment by Pompette** [comment]
You are welcome, yes there is auto detection, but it is not working very well, try with a better contrast between the page and the place you put it.

I decided to use manual either as I don't have the time to debug this for now.
